### ISSUE TITLE
Server Wont boot, after upgrade from 1.7.5 to 1.8

### ISSUE THREAD

**Issue by ImBehinYa** [DakotaPride/create-garnished#65]
Server Wont boot, after upgrade from 1.7.5 to 1.8

```
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'garnished'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[minecraft-1.20.1.i0:0/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.26.0-beta.2.jar:?]
at net.dakotapride.garnished.CreateGarnished.onInitialize(CreateGarnished.java:67) ~[garnished-1.81.20.1-fabric.i0:0/:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) ~[quilt-loader-0.26.0-beta.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_638
	at net.dakotapride.garnished.block.sepia.SepiaSignBlock.<init>(SepiaSignBlock.java:9) ~[garnished-1.81.20.1-fabric.i0:0/:?]
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.26.0-beta.2.jar:?]	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at net.dakotapride.garnished.block.sepia.SepiaSignBlock.<init>(SepiaSignBlock.java:9) ~[garnished-1.81.20.1-fabric.i0:0/:?]

	... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_638
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:202) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:174) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.26.0-beta.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:333) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.builders.BlockBuilder.createEntry(BlockBuilder.java:44) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.fabric.Lazy.get(Lazy.java:17) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate$Registration.register(AbstractRegistrate.java:121) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.AbstractRegistrate.onRegister(AbstractRegistrate.java:217) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]

	at com.tterrag.registrate.AbstractRegistrate.register(AbstractRegistrate.java:188) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]

	... 16 more	at com.tterrag.registrate.AbstractRegistrate.lambda$register$1(AbstractRegistrate.java:189) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at com.tterrag.registrate.fabric.RegistryUtil.forAllRegistries(RegistryUtil.java:12) ~[registrate-fabric-1.3.62-MC1.20.1.i0:0/:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.26.0-beta.2.jar:?]at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.26.0-beta.2.jar:?]	
	at net.dakotapride.garnished.CreateGarnished.onInitialize(CreateGarnished.java:67) ~[garnished-1.81.20.1-fabric.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.26.0-beta.2.jar:?]
```

**Comment by ImBehinYa** [comment]
1.7.5 boots, 1.8 doesnt

**Comment by DakotaPride** [comment]
Do you have a modlist? It could be an incompatibility with another mod.

**Comment by ImBehinYa** [comment]
<html><body><ul>
	<li>Controlify</li>
	<li>Extra Mod Integrations</li>
	<li>CTOV - Create: Structures</li>
	<li>Entity Model Features</li>
	<li>Incendium</li>
	<li>FerriteCore</li>
	<li>ThreadTweak</li>
	<li>Sodium Extra</li>
	<li>Entity Texture Features</li>
	<li>Create: Dreams &amp; Desires</li>
	<li>YUNG's Better Mineshafts</li>
	<li>Create Enchantment Industry</li>
	<li>End's Delight</li>
	<li>spark</li>
	<li>Pick Your Poison</li>
	<li>FabricSkyBoxes Interop</li>
	<li>What Are They Up To</li>
	<li>Concurrent Chunk Management Engine</li>
	<li>Architectury</li>
	<li>Krypton</li>
	<li>No Chat Reports</li>
	<li>Farmer's Delight</li>
	<li>FastQuit</li>
	<li>Our Villager Discounts</li>
	<li>Wandering Collector</li>
	<li>Debugify</li>
	<li>Creeper Spores</li>
	<li>Botarium</li>
	<li>Bobby</li>
	<li>CoroUtil</li>
	<li>Create: Storage</li>
	<li>Server Resource Pack Checker</li>
	<li>Noisium</li>
	<li>Additional Create Features</li>
	<li>CIT Resewn</li>
	<li>YUNG's Better Witch Huts</li>
	<li>ChoiceTheorem's Overhauled Village</li>
	<li>Ping Wheel</li>
	<li>YUNG's Extras</li>
	<li>Create: High Pressure</li>
	<li>Puzzles Lib</li>
	<li>Log Cleaner</li>
	<li>Moonlight</li>
	<li>YUNG's Better Nether Fortresses</li>
	<li>AppleSkin</li>
	<li>Enchancement</li>
	<li>Satin</li>
	<li>Create: Power Loader</li>
	<li>Iron Chests</li>
	<li>Icterine</li>
	<li>missions</li>
	<li>Ube's Delight</li>
	<li>Indium</li>
	<li>Jade Addons</li>
	<li>Decorative Blocks</li>
	<li>FabricSkyBoxes</li>
	<li>Handcrafted</li>
	<li>Not Enough Crashes</li>
	<li>Name Tag Tweaks</li>
	<li>YUNG's Better Strongholds</li>
	<li>View Distance Fix</li>
	<li>Lithostitched</li>
	<li>Recipe Cooldown</li>
	<li>Create: Interiors</li>
	<li>YUNG's Better Jungle Temples</li>
	<li>Observable</li>
	<li>Liquid Burner</li>
	<li>Consistency Plus</li>
	<li>EMI Trades</li>
	<li>Nvidium</li>
	<li>Expanded Delight</li>
	<li>MoreChatHistory</li>
	<li>Trinkets</li>
	<li>Resourceful Lib</li>
	<li>Simple Voice Chat Enhanced Groups</li>
	<li>YUNG's Bridges</li>
	<li>Create Diesel Generators</li>
	<li>Supplementaries</li>
	<li>Chipped</li>
	<li>Nullscape</li>
	<li>Cultural Creators</li>
	<li>Carpet Mod</li>
	<li>.index</li>
	<li>Frights Delight</li>
	<li>Tom's Simple Storage Mod</li>
	<li>Alternate Current</li>
	<li>No Resource Pack Warnings</li>
	<li>Sodium</li>
	<li>Create Cobblestone</li>
	<li>EMIffect</li>
	<li>Create: Structures</li>
	<li>ImmediatelyFast</li>
	<li>GeckoLib 4</li>
	<li>Supplementaries Squared</li>
	<li>Firework Frenzy</li>
	<li>Dynamic FPS</li>
	<li>Collective</li>
	<li>Nether's Delight Refabricated</li>
	<li>Simple Voice Chat Radio</li>
	<li>Terralith</li>
	<li>MixinTrace</li>
	<li>Mod Menu</li>
	<li>Right Click Harvest</li>
	<li>Sound Physics Remastered Create</li>
	<li>JamLib</li>
	<li>Create: Copycats+</li>
	<li>Just Enough Items</li>
	<li>World Specific View Distance</li>
	<li>Very Many Players</li>
	<li>Create Railways Navigator</li>
	<li>Memory Leak Fix</li>
	<li>Athena</li>
	<li>AdvancementInfo</li>
	<li>Respite Creators</li>
	<li>Cultural Delights Fabric</li>
	<li>Puzzle</li>
	<li>Create : Contraption Creatures</li>
	<li>Create: Garnished</li>
	<li>GeckoLibIrisCompat</li>
	<li>Continuity</li>
	<li>Capes</li>
	<li>YUNG's Better Desert Temples</li>
	<li>ModernFix</li>
	<li>LazyDFU</li>
	<li>Pickup Notifications</li>
	<li>YOSBR</li>
	<li>OptiGUI</li>
	<li>YUNG's Better Dungeons</li>
	<li>Jade</li>
	<li>Simple Trims</li>
	<li>Forge Config API Port</li>
	<li>Starlight</li>
	<li>Effective</li>
	<li>YetAnotherConfigLib</li>
	<li>Create: Numismatics</li>
	<li>Farmer's Respite</li>
	<li>YUNG's Better Ocean Monuments</li>
	<li>Create: Data and Plots</li>
	<li>Create: Power Loader</li>
	<li>Lithium</li>
	<li>Create: Armor Trims</li>
	<li>Fabric Language Kotlin</li>
	<li>Dynamic Crosshair</li>
	<li>Porting Lib</li>
	<li>Create: Big Contraptions</li>
	<li>Missions</li>
	<li>Main Menu Credits</li>
	<li>EMI Loot</li>
	<li>Comforts</li>
	<li>Model Gap Fix</li>
	<li>Create</li>
	<li>Dynamic Crosshair Compat</li>
	<li>Language Reload</li>
	<li>Create: Oxidized</li>
	<li>DisablePortalChecks</li>
	<li>Fabrishot</li>
	<li>YUNG's API</li>
	<li>oωo</li>
	<li>Slumber</li>
	<li>More Culling</li>
	<li>Inventory Sorter</li>
	<li>Create: New Age</li>
	<li>Animatica</li>
	<li>Create: Bells &amp; Whistles</li>
	<li>Fadeless</li>
	<li>ServerCore</li>
	<li>Superb Steeds</li>
	<li>Amendments</li>
	<li>Create Deco</li>
	<li>LambDynamicLights</li>
	<li>EntityCulling-Fabric</li>
	<li>Smarter Farmers</li>
	<li>Create: Numismatics</li>
	<li>AntiXray</li>
	<li>Create Ore Excavation</li>
	<li>EMI Ores</li>
	<li>Voice Chat Interaction</li>
	<li>Villager Names</li>
	<li>Garnished Additions</li>
	<li>Simple Voice Chat</li>
	<li>Iris Flywheel Compat</li>
	<li>Continents</li>
	<li>Terralith Andesite Patch</li>
	<li>Wiretap</li>
	<li>ToolTip Fix</li>
	<li>Better Mount HUD</li>
	<li>EMI</li>
	<li>Cloth Config v11</li>
	<li>YDM's Weapon Master</li>
	<li>Yeet</li>
	<li>Create Cobblestone</li>
	<li>Trowel</li>
	<li>EMI Enchanting</li>
	<li>YUNG's Better End Island</li>
	<li>Chunk Loader</li>
	<li>Enhanced Block Entities</li>
	<li>FDRF - Delightful Creators Recipe Fix</li>
	<li>e4mc</li>
	<li>Remove Reloading Screen</li>
	<li>Create: Food</li>
	<li>Delightful Creators</li>
	<li>Faster Random</li>
	<li>AzureLib</li>
	<li>Iris</li>
	<li>Create: Steam 'n' Rails</li>
	<li>Quilted Fabric API</li>
	<li>Borderless Mining</li>
	<li>Villager Transportation</li>
	<li>Reese's Sodium Options</li>
	<li>fabric-tab</li>
</ul></body></html>

**Comment by DakotaPride** [comment]
Not sure if this was a mistake, but there are some mods here that have double instances on the list. If this is actually the case and not a mistake while typing, I suggest first removing any instance of a mod that's listed twice here.

In the mean time, I'll look further into this.

**Comment by DakotaPride** [comment]
As a sidenote, if this is a public modpack, if you could link it here that would be appreciated (I couldn't find some of the mods listed above)

**Comment by ImBehinYa** [comment]
> but there are some mods here that have double instances on the list

No i just ripped the list of PRISM launcher, and some mods are disabled but still show up.


No it is private use, I could send you the download link private or I don't know.
As sending the link here would be Publishing?
And I didn't ask the modmakers for permission, as it is for private use. 

If you tell me which Mods I could provide sources an where I found them

**Comment by ImBehinYa** [comment]
Okay, maybe i didnt staste my issue clear enough.

I tried running my Quilt Server just with [(garnished 1.8)](https://modrinth.com/mod/create-garnished/version/1.8+1.20.1-fabric), [(ctreate patch f)](https://modrinth.com/mod/create-fabric/version/0.5.1-f-build.1417+mc1.20.1) and [(QFAPI 7.5.0 and QSL 6.1.2 )](https://modrinth.com/mod/qsl/version/7.5.0+0.91.0-1.20.1)

if i use 1.7.5 instead of 1.8 there is no issue

Client start and works without a Issue with 1.8 or 1.7.5

also tried quilkt loader from 0.25.0 upto beta4, for my modpack i need beta1 to 4 because quilt team is a bit slow and some mods requiere newer fabric loader

Hope this helps

**Comment by GameBurrow** [comment]
Can confirm the same happening with our modpack also: https://modrinth.com/modpack/transportcraft-lite/version/2.5.4
Using Fabric 0.15.11 and MC 1.20.1

Server log: https://gist.github.com/GameBurrow/a20918376da8ef65a7846364affa4c72

**Comment by DakotaPride** [comment]
Have you tested this in singleplayer as well? Might just be a server issue, I'm still looking through to see what might've gone wrong between versions.

**Comment by ImBehinYa** [comment]
Single player world works without issue, just server doesnt work

**Comment by GameBurrow** [comment]
Jep, works in singleplayer.

**Comment by DakotaPride** [comment]
Okay, I think I've found the issue (which, somehow, wasn't even related to anything changed in the update).

The problem was that the Sign blocks were getting a ResourceLocation from the client initializer class. These files haven't even been opened or modified since November, so I have no clue why it now has decided to all of a sudden pout about it.

I'll try to get the files updated later today (if not, sometime this weekend).
